version: '3'
services:
  app:
    build:
      context: docker/app
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  k6:
    image: grafana/k6:0.44.1
    entrypoint: sleep infinity
    volumes:
      - ./docker/k6:/home/k6
    environment:
      - TEST_APP_BASE_PATH=http://app:8080
      - K6_OUT=experimental-prometheus-rw
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM=true

  prometheus:
    image: prom/prometheus:v2.42.0
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:9.4.7
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./docker/grafana:/etc/grafana/provisioning/
